import math
RES = WIDTH, HEIGHT = 1200, 750
FPS = 200
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2

PLAYER_POS = 1.5, 5
PLAYER_ANG = 0
PLAYER_SP = 0.004
PLAYER_ROT = 0.002

FOV = math.pi /3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS